linphone/mswebrtc: fix build with gcc7
in file aec.c, remove unused const variable.

Because build fails with:

Sec.c:38:20: error: 'smooth_factor' defined but not used [-Werror=unused-const-variable=]
|  static const float smooth_factor = 0.05;
|                    ^~~~~~~~~~~~~

Signed-off-by: Pierre-Jean TEXIER <texier.pj2@gmail.com>